# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculadora_pb2 as calculadora__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculadora_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculadoraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Somar = channel.unary_unary(
                '/calculadora.v1.Calculadora/Somar',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.Subtrair = channel.unary_unary(
                '/calculadora.v1.Calculadora/Subtrair',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.Multiplicar = channel.unary_unary(
                '/calculadora.v1.Calculadora/Multiplicar',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.Dividir = channel.unary_unary(
                '/calculadora.v1.Calculadora/Dividir',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.Potencia = channel.unary_unary(
                '/calculadora.v1.Calculadora/Potencia',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.Modulo = channel.unary_unary(
                '/calculadora.v1.Calculadora/Modulo',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)
        self.RaizQuadrada = channel.unary_unary(
                '/calculadora.v1.Calculadora/RaizQuadrada',
                request_serializer=calculadora__pb2.OperacaoRequest.SerializeToString,
                response_deserializer=calculadora__pb2.OperacaoResponse.FromString,
                _registered_method=True)


class CalculadoraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Somar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtrair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiplicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dividir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Potencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Modulo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RaizQuadrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculadoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Somar': grpc.unary_unary_rpc_method_handler(
                    servicer.Somar,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'Subtrair': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtrair,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'Multiplicar': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiplicar,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'Dividir': grpc.unary_unary_rpc_method_handler(
                    servicer.Dividir,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'Potencia': grpc.unary_unary_rpc_method_handler(
                    servicer.Potencia,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'Modulo': grpc.unary_unary_rpc_method_handler(
                    servicer.Modulo,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
            'RaizQuadrada': grpc.unary_unary_rpc_method_handler(
                    servicer.RaizQuadrada,
                    request_deserializer=calculadora__pb2.OperacaoRequest.FromString,
                    response_serializer=calculadora__pb2.OperacaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculadora.v1.Calculadora', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculadora.v1.Calculadora', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculadora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Somar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Somar',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtrair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Subtrair',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiplicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Multiplicar',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dividir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Dividir',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Potencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Potencia',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Modulo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/Modulo',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RaizQuadrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculadora.v1.Calculadora/RaizQuadrada',
            calculadora__pb2.OperacaoRequest.SerializeToString,
            calculadora__pb2.OperacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
